name: Update data.json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Setup Git Profile
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Update data.json
      run: python3 update_data_json.py
    - name: Add and commit files
      run: |
        git add build/data.json
        set +e
        git diff --cached --quiet
        echo "##[set-output name=modified;]$?"
        set -e
      id: status_add
    - name: Commit files
      if: steps.status_add.outputs.modified == '1'
      run: |
        git commit -m "Update data.json"
    - name: Push changes
      if: steps.status_add.outputs.modified == '1'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages
